# Generated by Django 5.1.6 on 2025-08-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_order_referral_discount_order_referral_offer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='adminside.coupon'),
        ),
    ]
