# Generated by Django 5.1.6 on 2025-08-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_order_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrallink',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='referrallink',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReferralOffer',
        ),
        migrations.DeleteModel(
            name='ReferralLink',
        ),
    ]
