# Generated by Django 5.1.6 on 2025-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_referralcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcoupon',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
