# Generated by Django 5.1.6 on 2025-08-03 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_alter_referralcoupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcoupon',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='referralcoupon',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
