# Generated by Django 5.1.6 on 2025-08-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_remove_referralcoupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='referral_discount',
            new_name='referral_coupon_discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='referral_offer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='referral_coupons',
            field=models.ManyToManyField(blank=True, to='adminside.referralcoupon'),
        ),
    ]
