# Generated by Django 5.1.6 on 2025-08-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_rename_referral_discount_order_referral_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('razorpay', 'Razorpay')], max_length=30, null=True),
        ),
    ]
