# Generated by Django 5.1.6 on 2025-08-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0011_wallet_created_at_wallet_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_refunded_to_wallet',
            field=models.BooleanField(default=False),
        ),
    ]
