# Generated by Django 5.1.6 on 2025-08-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0012_order_is_refunded_to_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_refunded_to_wallet',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_refunded_to_wallet',
            field=models.BooleanField(default=False),
        ),
    ]
