# Generated by Django 5.1.6 on 2025-08-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0014_order_shipping_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
