# Generated by Django 5.1.6 on 2025-08-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0015_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to be refunded for this item', max_digits=10),
        ),
    ]
