# Generated by Django 5.1.6 on 2025-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0017_order_coupon_code_order_coupon_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_type',
            field=models.CharField(blank=True, choices=[('coupon', 'Coupon'), ('referral', 'Referral Coupon')], max_length=20, null=True),
        ),
    ]
