# Generated by Django 5.1.6 on 2025-08-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0018_order_coupon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_refunded_to_wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
