# Generated by Django 5.1.6 on 2025-08-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0019_order_total_refunded_to_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_refunded_to_wallet',
        ),
    ]
