# Generated by Django 5.1.6 on 2025-08-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0020_remove_order_total_refunded_to_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon_discount_applied',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
