# Generated by Django 5.1.6 on 2025-08-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0021_orderitem_coupon_discount_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='coupon_discount_applied',
        ),
    ]
