# Generated by Django 5.1.6 on 2025-08-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_customuser_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
