# Generated by Django 5.1.6 on 2025-08-10 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0004_alter_customuser_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
