# Generated by Django 5.1.6 on 2025-08-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0005_emailotp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='expires_at',
        ),
    ]
