# Generated by Django 5.1.6 on 2025-08-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0007_emailotp_expires_at_emailotp_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset')], default='registration', max_length=20),
        ),
    ]
