# Generated by Django 5.1.6 on 2025-08-21 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0008_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
